//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function.
func (in *TSecret) DeepCopyInto(out *TSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *TSecret) DeepCopy() *TSecret {
	if in == nil {
		return nil
	}
	out := new(TSecret)
	in.DeepCopyInto(out)
	return out
}

func (in *TSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TSecretList) DeepCopyInto(out *TSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *TSecretList) DeepCopy() *TSecretList {
	if in == nil {
		return nil
	}
	out := new(TSecretList)
	in.DeepCopyInto(out)
	return out
}

func (in *TSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TSecretStore) DeepCopyInto(out *TSecretStore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *TSecretStore) DeepCopy() *TSecretStore {
	if in == nil {
		return nil
	}
	out := new(TSecretStore)
	in.DeepCopyInto(out)
	return out
}

func (in *TSecretStore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TSecretStoreList) DeepCopyInto(out *TSecretStoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TSecretStore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *TSecretStoreList) DeepCopy() *TSecretStoreList {
	if in == nil {
		return nil
	}
	out := new(TSecretStoreList)
	in.DeepCopyInto(out)
	return out
}

func (in *TSecretStoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ClusterTSecretStore) DeepCopyInto(out *ClusterTSecretStore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ClusterTSecretStore) DeepCopy() *ClusterTSecretStore {
	if in == nil {
		return nil
	}
	out := new(ClusterTSecretStore)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterTSecretStore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ClusterTSecretStoreList) DeepCopyInto(out *ClusterTSecretStoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterTSecretStore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ClusterTSecretStoreList) DeepCopy() *ClusterTSecretStoreList {
	if in == nil {
		return nil
	}
	out := new(ClusterTSecretStoreList)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterTSecretStoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TSecretSync) DeepCopyInto(out *TSecretSync) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *TSecretSync) DeepCopy() *TSecretSync {
	if in == nil {
		return nil
	}
	out := new(TSecretSync)
	in.DeepCopyInto(out)
	return out
}

func (in *TSecretSync) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TSecretSyncList) DeepCopyInto(out *TSecretSyncList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TSecretSync, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *TSecretSyncList) DeepCopy() *TSecretSyncList {
	if in == nil {
		return nil
	}
	out := new(TSecretSyncList)
	in.DeepCopyInto(out)
	return out
}

func (in *TSecretSyncList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto helpers for spec types

func (in *TSecretSpec) DeepCopyInto(out *TSecretSpec) {
	*out = *in
	out.EncryptionRef = in.EncryptionRef
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]TSecretEntry, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *TSecretStatus) DeepCopyInto(out *TSecretStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastEncryptedAt != nil {
		in, out := &in.LastEncryptedAt, &out.LastEncryptedAt
		*out = (*in).DeepCopy()
	}
}

func (in *TSecretStoreSpec) DeepCopyInto(out *TSecretStoreSpec) {
	*out = *in
	in.Provider.DeepCopyInto(&out.Provider)
}

func (in *SecretStoreProvider) DeepCopyInto(out *SecretStoreProvider) {
	*out = *in
	if in.Vault != nil {
		in, out := &in.Vault, &out.Vault
		*out = new(VaultProvider)
		**out = **in
	}
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(AWSProvider)
		**out = **in
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(AzureProvider)
		**out = **in
	}
	if in.GCP != nil {
		in, out := &in.GCP, &out.GCP
		*out = new(GCPProvider)
		**out = **in
	}
	if in.Oracle != nil {
		in, out := &in.Oracle, &out.Oracle
		*out = new(OracleProvider)
		**out = **in
	}
}

func (in *TSecretStoreStatus) DeepCopyInto(out *TSecretStoreStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastCheckedAt != nil {
		in, out := &in.LastCheckedAt, &out.LastCheckedAt
		*out = (*in).DeepCopy()
	}
}

func (in *TSecretSyncSpec) DeepCopyInto(out *TSecretSyncSpec) {
	*out = *in
	out.SecretStoreRef = in.SecretStoreRef
	out.Target = in.Target
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make([]TSecretSyncData, len(*in))
		copy(*out, *in)
	}
}

func (in *TSecretSyncStatus) DeepCopyInto(out *TSecretSyncStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncedAt != nil {
		in, out := &in.LastSyncedAt, &out.LastSyncedAt
		*out = (*in).DeepCopy()
	}
}
