# Manifest de laboratório — Vault → TSecret (namespace tsecret-test)
apiVersion: tsecret.io/v1alpha1
kind: TSecretSync
metadata:
  name: db-pass-sync
  namespace: tsecret-test
spec:
  secretStoreRef:
    name: vault-backend
    kind: TSecretStore
  target:
    name: db-credentials
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: db-pass
        property: value
    - secretKey: DB_PASSWORD2
      remoteRef:
        key: db-pass2
        property: value
  refreshInterval: "30s"
