{{- if and .Values.poc.enabled .Values.poc.externalSecrets.createClusterSecretStore }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.poc.externalSecrets.clusterSecretStore }}
  labels:
    {{- include "tsecret.labels" . | nindent 4 }}
    app.kubernetes.io/component: poc-external-secrets
spec:
  provider:
    vault:
      server: {{ .Values.poc.externalSecrets.vault.server | quote }}
      path: {{ .Values.poc.externalSecrets.vault.path | quote }}
      version: v2
      auth:
        tokenSecretRef:
          name: {{ .Values.poc.externalSecrets.vault.tokenSecretRef.name }}
          key: {{ .Values.poc.externalSecrets.vault.tokenSecretRef.key }}
          namespace: {{ include "tsecret.vaultAuthSecretNamespace" . }}
{{- end }}
