{{- if and .Values.poc.enabled .Values.poc.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.poc.externalSecrets.externalSecret.name }}
  namespace: {{ include "tsecret.pocNamespace" . }}
  labels:
    {{- include "tsecret.labels" . | nindent 4 }}
    app.kubernetes.io/component: poc-external-secrets
spec:
  refreshInterval: {{ .Values.poc.externalSecrets.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.poc.externalSecrets.clusterSecretStore }}
  target:
    name: {{ .Values.poc.vault.auth.existingSecret.name }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.poc.vault.auth.existingSecret.key }}
      remoteRef:
        key: {{ .Values.poc.vault.auth.existingSecret.name }}
        property: {{ .Values.poc.vault.auth.existingSecret.key }}
{{- end }}
