{{- if and .Values.poc.enabled (eq .Values.poc.vault.auth.method "direct") (not .Values.poc.externalSecrets.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.poc.vault.auth.existingSecret.name }}
  namespace: {{ include "tsecret.vaultAuthSecretNamespace" . }}
  labels:
    {{- include "tsecret.labels" . | nindent 4 }}
    app.kubernetes.io/component: poc-vault-auth
type: Opaque
stringData:
  {{ .Values.poc.vault.auth.existingSecret.key }}: {{ .Values.poc.vault.auth.token | quote }}
{{- end }}
